### ISSUE TITLE
Public java API

### ISSUE THREAD

**Issue by rejsmont** [mcib3d/mcib3d-plugins#1]
The macro API works really nice, however it would be even nicer to have a proper Java API. This would enable scripting this plugin in Java or Jython.

**Comment by mcib3d** [comment]
Dear Rejsmont,

Thanks for your message, yes we are working on the documentation ;) of the core library, these plugins are examples of applications of core objects. 

best,

Thomas

**Comment by rejsmont** [comment]
I had a look at how plugins are written and now the core library seems quite self-explanatory. Thank you for a great library and for making it open source!

**Comment by mcib3d** [comment]
Thank you for your message, we are happy to share our work, feedbacks are most welcome !

Best
