### ISSUE TITLE
Measure 3D blocks ImageJ

### ISSUE THREAD

**Issue by stelfrich** [mcib3d/mcib3d-plugins#11]
In the current implementation, Measure 3D is executed on the EDT (see [RoiManager3D_2.java#L1201](https://github.com/mcib3d/mcib3d-plugins/blob/master/src/main/java/mcib_plugins/tools/RoiManager3D_2.java#L1201)), thus blocking the complete user interface during computations. While this might not be an issue for most of the measures, it is a big deal when computing convex hulls for several objects in an image.

It would be super useful to have the computation executed on a different thread, so that the ImageJ UI remains responsive.

**Comment by mcib3d** [comment]
Hi Stef,

I suppose it is a good idea, but only in GUI mode, in macro mode it will go to the next line without waiting Measure3D to finish. If you feel confident to modify the code, please submit a pull request, else I will try to do it. 

Best,

Thomas

**Comment by mcib3d** [comment]
Hi Stef,

The new version has an improved interface that does not freeze when actioning buttons. b265cbfcc1fffabdf24abe905590ac6b4734d585

Best,

Thomas

**Comment by stelfrich** [comment]
Thanks for the update, Thomas! 👍
