### ISSUE TITLE
use with movies

### ISSUE THREAD

**Issue by tischi** [mcib3d/mcib3d-plugins#13]
Hello,
Are there any options to use the 3-D Image Suite on a hyper-stack with z and **time** axis?

**Comment by mcib3d** [comment]
Hi,
Humm that has been on my To Do list for a long time, the idea is when a 4D stack is detected, we duplicate the active time frame and use this as 3D input to 3DManager. This is what I do in macro but yes it should be automated. 
best,
Thomas

**Comment by mcib3d** [comment]
Hi,

Should be fixed in latest commit 932d502b3b62358ea16191e33e07c82ec23d4f05 .

Thomas

**Comment by tischi** [comment]
Hi,

Thank you! I will test it soon!

Christian
