### ISSUE TITLE
What do the radii correspond to?

### ISSUE THREAD

**Issue by tejojala123** [mcib3d/mcib3d-plugins#14]
hello, 
What do the values of the three radii correspond to? 
Do they refer to the half principle axes of the fitted ellipsoids?  

given by the equation:
{x^{2} \over a^{2}}+{y^{2} \over b^{2}}+{z^{2} \over c^{2}}=1,

Also, what is the difference between Ferret 1 and 2 and pole 1 and 2?

thanks
best
tejojala

**Comment by mcib3d** [comment]
Hello,

The equation refers to the description of an ellipsis in 3D, so after ellipsoid fitting, the two poles are the two most distant point along the main axis. The points Feret 1 and Feret 2 are tho two points defining the Feret diameter of the object, or the two most distant points of the object, if the object is an ellipsoid of course the poles will be the feret points.
Hope this helps
Thomas

**Comment by tejojala123** [comment]
Hello Thomas, 
Thank you for your quick reply. 

Just to clarify, R1,R2,R3 are a,b,c from this equation right?
![equation](https://cloud.githubusercontent.com/assets/17988915/23945606/15c6c078-09b2-11e7-9fb1-c9df3edc8530.png)

And the corresponding ellipse is like 
![ellipsoid](https://cloud.githubusercontent.com/assets/17988915/23945630/2b1152ae-09b2-11e7-94a1-fbe3e6b4c458.png)

Thanks 
Tejojala

**Comment by mcib3d** [comment]
Hi,
Yes basically _R1_, _R2_ and _R3_ are the three radii and corresponds to _a_, _b_ and _c_. However note than the three radii _R1_, _R2_ and _R3_ are sorted (_R1_ largest value) and that the axes of the fitted ellipsoid may not be the canonical axes _x_, _y_ and _z_.
Best,
Thomas

**Comment by tejojala123** [comment]
Thanks for the clarification, 
Best 
Telojala
