### ISSUE TITLE
Crop3D_All (deprecated) - 1) Why deprecated? 2) Error with 32-bit float images.

### ISSUE THREAD

**Issue by pdd2110** [mcib3d/mcib3d-plugins#19]
Hello,

As part of our processing pipeline, we are cropping multiple ROIs from 3D multichannel images. The images are 32-bit, with some of the channels having signed values. Currently we split the channels, then, in a for loop that iterates through the channels, we call the `Crop3D_All (deprecated)` function to run through the entire ROI list and save the indexed cropped regions automatically. All of our code is written in the IJ1 macro language. We really like this function as it does exactly what we need and is incredibly fast. I have two questions, however:

1. Why is this function deprecated? Is there a reason we should not be using it? And if so, would we be able to bypass these issues while maintaining the same performance by running `Crop3D` in a for loop?
2. We get an error message when we try to run 32-bit Float images. Is it possible to override the error? 

As far as (2) goes, I wrote a workaround back in December, and an unrelated bug reminded me to ask about it. I haven't revisited the issue since then, but as far as I can tell from (a cursory glance at) the code, both `Crop3D_All (deprecated)` and `Crop3D` are limited to 8- or 16-bit images. That said, they both operate by calling `cropRadius`, which makes an appearance in `imageFloat`. I assume this latter one enables mcib3d-suite to handle 32-bit float images. Not sure if this patched it or if its still an issue.

In case you're interested, here's the workaround: 
We're converting the 32-bit image to 16-bit, acquire intensity statistics before and after, running the cropping function, converting from 16 to 32, then reversing any intensity changes using the acquired stats. 

Figured I might inquire. Thanks!

**Comment by mcib3d** [comment]
Hi,

Actually this plugin is marked deprecated as it may change name or functionality later. It is just I am not very happy with this plugin and I think it should be redesigned. However, for the time being you are welcome to use it and suggest improvements. 

I fixed the fact that this plugin was only working for 8 or 16 bits image, in a next release it should work on 32-bit images as well.

Best,

**Comment by pdd2110** [comment]
Thank you Thomas, really appreciate it!

Two follow-ups:
1) has the code currently on GitHub integrated this feature (and is it stable)? Just thinking I could go ahead and create a temp jar now to get started ironing out the kinks.
2) When do you think you’ll be dropping the update? Just want to put in a reminder for myself to rejigger our code thenabouts.


P

Sent from iPhone

On Mar 4, 2021, at 04:11, Thomas BOUDIER <notifications@github.com> wrote:

﻿

Hi,

Actually this plugin is marked deprecated as it may change name or functionality later. It is just I am not very happy with this plugin and I think it should be redesigned. However, for the time being you are welcome to use it and suggest improvements.

I fixed the fact that this plugin was only working for 8 or 16 bits image, in a next release it should work on 32-bit images as well.

Best,

**Comment by mcib3d** [comment]
Hi,

The fix has been committed, hopefully this week it will released in Fiji.

Best,

**Comment by pdd2110** [comment]
Thank you Thomas, I really appreciate it!

All the best,
Patrick

Sent from iPhone

On Mar 9, 2021, at 04:41, Thomas BOUDIER ***@***.***> wrote:

﻿

Hi,

The fix has been committed, hopefully this week it will released in Fiji.

Best,
