### ISSUE TITLE
remove objects touching image edges

### ISSUE THREAD

**Issue by tischi** [mcib3d/mcib3d-plugins#2]
I could not find a function to automatically remove all objects from a label image, which touch the image boundaries. I think this would be very important as in most of the cases such objects need to be discarded from the analysis.

**Comment by mcib3d** [comment]
Hi,

If you "add a image" into 3Dmanager if there is a ROI, only the objects having centers inside the ROI will be added.

**Comment by mcib3d** [comment]
Hi,

In 3DManager there is a option "Exclude objects on edges XY" and also "Z". The function is in Object3D 

 public boolean edgeImage(ImageHandler img, boolean edgeXY, boolean edgeZ)

You also have the function in 3DobjectsPopulation 

 public void removeObjectsTouchingBorders(ImagePlus img, boolean Z)

**Comment by tischi** [comment]
Hi,
thank you for the answer! I checked the code but I am not sure how to use it for (jython) scripting.
right now, I have code up to a point where I obtain a label image (imp_label), which for instance serves as an input to IJ.run(imp_label, "3D Geometrical Measure", ""), is is possible to somehow write a function like this
imp_label_no_boundary_objects = remove_boundary_objects_from_label_image(imp_label)
?

**Comment by mcib3d** [comment]
Hi,
Humm I would prefer to add a option to the 3D Analysis plugin like "remove objects on edges", like what we have in 3DManager. Sounds ok for you ?

**Comment by tischi** [comment]
Hi, 
I guess the input to this plugin would be a label image and the output would be a label image with the boundary objects removed, right? If so, then yes I think this would be great! In fact this is exactly what i meant to say above.

**Comment by mcib3d** [comment]
New plugin 3e433ce3b0744670d318c13bf2dbe89a329f65a8
