### ISSUE TITLE
3D Intensity Measure

### ISSUE THREAD

**Issue by tischi** [mcib3d/mcib3d-plugins#3]
Running **3D Intensity Measure** produces a table _without_ a column called **label**.
In contrast **3D Geometrical Measure** has a **label** column.
I think it  would be very good if 3D Intensity Measure also had the label column in order to know from which object each measurement comes.

**Comment by mcib3d** [comment]
Hi,

Correctd and updated in commit d50bf9d5d8da14ccba8d49b101a16bd7ba6a0666.
