### ISSUE TITLE
surface_to_volume_ratio criterion for iterative thresholding

### ISSUE THREAD

**Issue by tischi** [mcib3d/mcib3d-plugins#4]
Hi,
I was wondering about an additional criterium for the iterative thresholding, namely the Surface to Volume Ratio. This is minimal for spheres and thus should select for smooth and round objects. The reason I am suggesting this is that the current **Elongation** criterium for me selects sometimes too low thresholds, where only the  "interior" of the objects is selected. I think the issue is that the ellipsoidal fit does have no notion of surface smoothness, but I think only measures where the object is symmetrical, so it can be very rugged. I think it would be very interesting to test the surface_to_volume_ratio criterion for finding thresholds selecting smooth and round objects. 
Best, Christian

**Comment by mcib3d** [comment]
Hi,
Computing surface in digital images is quite tricky, and can vary a lot particularly for small objects, when the surface is not "smooth". Elongation seems a more robust measure. 
But yes, in some cases, the **compacity** criterium sounds good, however we have implemented many variants in 3DManager, can you check which one is working fine for you. 
Best,
Thomas

**Comment by mcib3d** [comment]
Hi,

It was implemented in c8bc64b1b6a715ab7149a66541cd6838878677b2. 

Thomas
