### ISSUE TITLE
hyperstack

### ISSUE THREAD

**Issue by tischi** [mcib3d/mcib3d-plugins#5]
Hello,
I just realized the the plugins do not properly work with hyperstacks (e.g. [File>Open Samples>Mitosis]). I think this would be very important as multi-color time-lapse applications are kind of standard these days.

**Comment by mcib3d** [comment]
Hi,
Yes, thanks to Wayne Rasband,  only the ImageJ version of fastfilters is working with 5D images. I did not implement the use for 4D or 5D images because it can be done easily with macros. I will then add some macros for 4D/5D on the website.

**Comment by tischi** [comment]
..I am curious: what does "ImageJ version" mean? is this different to "Fiji version"?

**Comment by mcib3d** [comment]
Hi,

Humm same, the 3D filters located in Process/Filters, median3D, ...

**Comment by tischi** [comment]
Hi, ok...in which sense are those "fast filters"?
http://rsb.info.nih.gov/ij/plugins/gaussian-blur-3d/Gaussian_Blur_3D.java
doesn't look multi-core to me, or?

**Comment by mcib3d** [comment]
Hi,
Gaussian 3D is the only 3D filter not written by me, so maybe not multi-core ;) . The other 3D filters should be multi-core.

**Comment by tischi** [comment]
Hi Thomas, ok! I did not know this!
But I feel you would recommend using the 3D Suite in general because it is more consistent and up-to-date, isn't it?

**Comment by mcib3d** [comment]
in the FastFilters3D plugin of the 3D suite, there are more filters available, so yes ;)
