### ISSUE TITLE
RoiManager3D settings do not work

### ISSUE THREAD

**Issue by metalico** [mcib3d/mcib3d-plugins#6]
In mcib3d_plugins3.7, class RoiManager3D_2.java, line 1240 you have this code:

  private void buttonConfigActionPerformed(ActionEvent evt) {
    IJ.run("3D Manager Options");
  }

And it should be:

  private void buttonConfigActionPerformed(ActionEvent evt) {
    IJ.run("RoiManager3D_Options");
  }

It won't recognize the command otherwise and the window won't launch. I'm having trouble with it because there are lots of errors when I decompile the jar file to correct it. Could you please upload a new version? Thanks a lot!

**Comment by mcib3d** [comment]
Hi Metalico,

It is working perfectly well on my system, and nobody reported any pb. The IJ.run methods works with command name, that is the name of the plugin as it appears in the menu, not the name of the class. If you modify the name of the plugin in the menu, it won´t work . Hope this helps.

Thomas

**Comment by metalico** [comment]
Hi Thomas,

Thank you very much for your answer. I am trying to correct other people's ImageJ version and this is one of the problems. I'll start with your advice to solve it.

Thank you again!
