### ISSUE TITLE
Some tools work for 3D only

### ISSUE THREAD

**Issue by tischi** [mcib3d/mcib3d-plugins#8]
Hello,

Some of the tools already work for both 3D and 2D, others only work for 3D. 

As this suite is useful for general purpose image analysis it would be great if **all** the tools would also work for 2D input images. 

Is that something feasible or am I asking too much?

**Comment by mcib3d** [comment]
Hi @tischi ,

I try to make my tools work in 3D first and 2D in the case there is no already existing 2D plugins. Can you give me a list of plugins that does not work for 2D ? Thanks.

Thomas

**Comment by mcib3d** [comment]
Hi,

The useful binaryCloseLabel plugin now works with 2D images. 469e79816d95c7dd0af6cdbebef3f4b06c1906fe

Thomas

**Comment by tischi** [comment]
Hi!
Thanks  a lot!
Please excuse me for not yet answering your question above! 
I was totally distracted with other stuff at work.
